
import React from 'react';
import Head from 'next/head'
import Layout from '@/components/Layout'
import Image from 'next/image'
import profilepic from '../../public/images/profile/developer-pic-1.png';
import AnimatedText from '@/components/AnimatedText';
import Link from "next/link";
import { LinkArrow } from '@/components/Icons';
import HireMe from '@/components/HireMe';
import lightBulb from "../../public/images/svgs/miscellaneous_icons_1.svg"
import TransitionEffect from "@/components/TransitionEffect"
export default function Home() {
  return (
    <>
  <Head>
    <title>City Scooter</title>
    <meta name ='description' content='generated by create next app' />
  </Head>

  
  <TransitionEffect/>
      
      <main
      dir='rtl'
      
      className='flex items-center  text-dark w-full min-h-screen dark:text-light'>
        {/* Your main content here */}
        
      <Layout
      className='pt-0 md:pt-16 sm:pt-8'
      >
        
        <div className='flex items-center  justify-between w-full lg:flex-col'>
        <div className='w-1/2 md:} w-full'>
            <Image src={profilepic} alt='codebucks' className='w-full h-auto lg:hidden md:inline-block md:w-full'/>
          </div>
          <div className='w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center'>
            
            <AnimatedText text="تحويل الرؤية إلى واقع باستخدام الكود والتصميم."
            className='!text-6xl !text-right xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl
            '
             />
            <p className='my-4 text-base font-medium md:text-sm  sm:text-xs'>
            باعتباري مطورًا ماهرًا، فأنا ملتزم بتحويل الأفكار إلى تطبيقات ويب مبتكرة. استكشف أحدث مشاريعي ومقالاتي، واعرض خبرتي في React.js وتطوير الويب
            </p>
            <div className='flex items-center self-start mt-2 lg:self-center'>
              <Link href='/dummy.pdf' target={"_blank"}
              className='flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark 
              border-2 border-solid border-transparent hover:border-dark md:p-2 md:px-4 md:text-base
               dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light hover:dark:border-light '
              download={true} >
              <LinkArrow className={"w-6 ml-1"}/>
             
               الحجز</Link>
              <Link href='mailto:abcd@gmail.com' target={"_blank"}
              className='mr-4 p-2 text-lg font-medium capitalize text-dark dark:text-light underline offset-2 md:text-base'
              >الاتصال</Link>
            </div>
          </div>
         
        </div>
      </Layout>
      <HireMe />
      <div 
      className='absolut ml-14 mb-20 inline-block w-24 md:hidden'>
      <Image src={lightBulb} alt="city scooter" className='w-full h-auto'/>

      </div>
      </main>
    </>
  )
}
